[package]
name = "vk_llw"
version = "0.1.0"
authors = ["KirFed <f3lkilo@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.31.0"
log = "0.4.11"

[dev-dependencies]
env_logger = "0.8.2"